### ISSUE TITLE
ignore size error

### ISSUE THREAD

**Issue by kall666** [private-dreamnet/dreampower#56]
F:\dreampower>python main.py -i 123.jpg --ignore-size
[INFO] Welcome to DreamPower
[INFO] GAN Processing Will Use GPU IDs: [0]
[WARNING] Image Size Requirements Unchecked.
[INFO] Executing Image Transform
[INFO] Processing on 123.jpg
[INFO] Executing Dress To Correct
[INFO] Executing Correct To Mask
[INFO] Executing Mask To Maskref
Traceback (most recent call last):
  File "main.py", line 144, in <module>
    argv.ArgvParser.run()
  File "F:\dreampower\argv.py", line 373, in run
    args.func(args)
  File "F:\dreampower\main.py", line 33, in main
    select_processing().run()
  File "F:\dreampower\processing\__init__.py", line 40, in run
    self._execute()
  File "F:\dreampower\processing\__init__.py", line 163, in _execute
    r = p.run(*[self.__image_steps[i] for i in p.input_index])
  File "F:\dreampower\transform\__init__.py", line 29, in run
    r = self.execute(*args)
  File "F:\dreampower\transform\opencv\mask.py", line 47, in execute
    res1 = cv2.bitwise_and(correct, correct, mask=green_mask_inv)
cv2.error: OpenCV(4.1.0) C:\projects\opencv-python\opencv\modules\core\src\arithm.cpp:245: error: (-215:Assertion failed) (mtype == CV_8U || mtype == CV_8S) && _mask.sameSize(*psrc1) in function 'cv::binary_op'

**Comment by deeppppp** [comment]
--ignore-size will result in errors at this time.
the GANs require a 512x512 input image.

work in progress :)
